# Generated by Django 3.2 on 2021-04-27 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HasSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('login', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FileSection',
            fields=[
                ('hassection_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='filesystem.hassection')),
                ('optional_name', models.CharField(blank=True, max_length=256, verbose_name='name')),
                ('optional_desc', models.TextField(blank=True, verbose_name='optional description')),
                ('creation_date', models.DateTimeField(verbose_name='creation date')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_has_section', to='filesystem.hassection')),
            ],
            bases=('filesystem.hassection',),
        ),
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('optional_desc', models.TextField(blank=True, verbose_name='optional description')),
                ('creation_date', models.DateTimeField(verbose_name='creation date')),
                ('availability_flag', models.BooleanField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filesystem.user')),
            ],
        ),
        migrations.CreateModel(
            name='SectionCategory',
            fields=[
                ('file_section', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='filesystem.filesection')),
                ('category_type', models.CharField(choices=[('PROC', 'Procedure'), ('PROP', 'Property'), ('LEM', 'Lemma'), ('ASRT', 'Assert'), ('INV', 'Lemma'), ('PREC', 'Precondition'), ('POST', 'Postcondition')], default='PROC', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='SectionStatus',
            fields=[
                ('file_section', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='filesystem.filesection')),
                ('category_type', models.CharField(choices=[('PROV', 'Proved'), ('INV', 'Invalid'), ('COUN', 'Counterexample'), ('UNCH', 'Unchecked')], default='UNCH', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('hassection_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='filesystem.hassection')),
                ('name', models.CharField(max_length=256)),
                ('file_data', models.FileField(upload_to='')),
                ('optional_desc', models.TextField(blank=True, verbose_name='optional description')),
                ('creation_date', models.DateTimeField(verbose_name='creation date')),
                ('availability_flag', models.BooleanField()),
                ('directory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filesystem.directory')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filesystem.user')),
            ],
            bases=('filesystem.hassection',),
        ),
        migrations.CreateModel(
            name='StatusData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filesystem.user')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filesystem.sectionstatus')),
            ],
        ),
    ]
