# Generated by Django 3.2 on 2021-04-27 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filesystem', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filesection',
            old_name='optional_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='directory',
            name='optional_desc',
        ),
        migrations.RemoveField(
            model_name='file',
            name='optional_desc',
        ),
        migrations.RemoveField(
            model_name='filesection',
            name='optional_desc',
        ),
        migrations.AddField(
            model_name='directory',
            name='desc',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='file',
            name='desc',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='filesection',
            name='desc',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_data',
            field=models.FileField(upload_to='', verbose_name='file'),
        ),
    ]
