# Generated by Django 3.2 on 2021-04-27 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filesystem', '0002_auto_20210427_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directory',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='file',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='statusdata',
            name='owner',
        ),
    ]
