# Generated by Django 3.2.3 on 2021-05-22 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import verifier.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=256)),
                ('login', models.CharField(max_length=40, unique=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WithSections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='FileSection',
            fields=[
                ('withsections_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='verifier.withsections')),
                ('name', models.CharField(blank=True, max_length=256)),
                ('desc', models.TextField(blank=True)),
                ('creation_date', models.DateTimeField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_parent', to='verifier.withsections')),
            ],
            bases=('verifier.withsections',),
        ),
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=256)),
                ('desc', models.TextField(blank=True)),
                ('creation_date', models.DateTimeField()),
                ('availability_flag', models.BooleanField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='verifier.directory')),
            ],
        ),
        migrations.CreateModel(
            name='SectionCategory',
            fields=[
                ('file_section', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='verifier.filesection')),
                ('category_type', models.CharField(choices=[('proc', 'Procedure'), ('prop', 'Property'), ('lemma', 'Lemma'), ('assert', 'Assert'), ('inv', 'Invariant'), ('var', 'Variant'), ('precond', 'Precondition'), ('postcond', 'Postcondition')], default='inv', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='SectionStatus',
            fields=[
                ('file_section', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='verifier.filesection')),
                ('category_type', models.CharField(choices=[('prov', 'Proved'), ('inv', 'Invalid'), ('counter', 'Counterexample'), ('unch', 'Unchecked')], default='unch', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('withsections_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='verifier.withsections')),
                ('name', models.TextField(max_length=256)),
                ('file_cont', models.FileField(upload_to=verifier.models.upload_path, verbose_name='file')),
                ('desc', models.TextField(blank=True)),
                ('creation_date', models.DateTimeField(verbose_name='creation date')),
                ('availability_flag', models.BooleanField()),
                ('directory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verifier.directory')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('verifier.withsections',),
        ),
        migrations.CreateModel(
            name='StatusData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verifier.sectionstatus')),
            ],
        ),
    ]
